const KEY='control_empresarial_v4';
let db=load();
const $=id=>document.getElementById(id),today=()=>new Date().toISOString().slice(0,10);
function load(){try{return Object.assign({investments:[],products:[],sales:[],expenses:[],rates:{USD:360,EUR:390}},JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return {investments:[],products:[],sales:[],expenses:[],rates:{USD:360,EUR:390}}}}
function save(){localStorage.setItem(KEY,JSON.stringify(db));render()}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2)}
function inv(id){return db.investments.find(x=>x.id===id)} function prod(id){return db.products.find(x=>x.id===id)}
function rate(c){return c==='USD'?+db.rates.USD:c==='EUR'?+db.rates.EUR:1}
function cup(v,c,r=rate(c)){return (+v||0)*(+r||1)}
function money(v){return new Intl.NumberFormat('es-ES',{maximumFractionDigits:2}).format(+v||0)+' CUP'}
function fmt(v,c){return new Intl.NumberFormat('es-ES',{maximumFractionDigits:2}).format(+v||0)+' '+c}
function landed(p){const i=inv(p.invId);if(!i)return cup(p.cost,p.cur);const ps=db.products.filter(x=>x.invId===i.id);let ship=0;if(i.alloc==='qty')ship=(+i.ship||0)/(ps.reduce((a,x)=>a+(+x.qty||0),0)||1);else{const total=ps.reduce((a,x)=>a+(+x.cost||0)*(+x.qty||0),0)||1;ship=(+i.ship||0)*((+p.cost||0)*(+p.qty||0)/total)/(+p.qty||1)}return cup(p.cost,p.cur)+cup(ship,i.cur,i.rateSnapshot||rate(i.cur))}
function recovery(i){let r=0,date=null;db.sales.filter(s=>prod(s.prodId)?.invId===i.id).sort((a,b)=>a.date.localeCompare(b.date)).forEach(s=>{const p=prod(s.prodId);r+=landed(p)*s.qty;if(!date&&r>=cup(i.total,i.cur,i.rateSnapshot||rate(i.cur)))date=s.date});const target=cup(i.total,i.cur,i.rateSnapshot||rate(i.cur));return{r,target,date,pct:target?Math.min(100,r/target*100):0}}
function metrics(){const invested=db.investments.reduce((a,i)=>a+cup(i.total,i.cur,i.rateSnapshot||rate(i.cur)),0),sales=db.sales.reduce((a,s)=>a+cup(s.price*s.qty,s.cur,s.rateSnapshot||rate(s.cur)),0),cost=db.sales.reduce((a,s)=>{const p=prod(s.prodId);return a+(p?landed(p)*s.qty:0)},0),expenses=db.expenses.reduce((a,e)=>a+cup(e.amt,e.cur,e.rateSnapshot||rate(e.cur)),0);return{invested,sales,cost,expenses,gross:sales-cost,net:sales-cost-expenses}}
function nav(p){document.querySelectorAll('main>section').forEach(s=>s.classList.add('hidden'));const section=$(p);if(section)section.classList.remove('hidden');document.querySelectorAll('.side nav button').forEach(b=>b.classList.toggle('active',b.dataset.p===p));document.querySelectorAll('.bottom button[data-mobile-p]').forEach(b=>b.classList.toggle('active',b.dataset.mobileP===p));const t={dashboard:['Resumen financiero','Visión general de tu negocio'],investments:['Inversiones','Pedidos y capital comprometido'],inventory:['Inventario','Productos, identificadores y stock'],sales:['Ventas','Registra una venta sin salir de esta pantalla'],expenses:['Gastos','Costos operativos del negocio'],reports:['Reportes','Indicadores para tomar decisiones'],settings:['Ajustes','Preferencias, divisas y respaldo']}[p];if(t){$('title').textContent=t[0];$('subtitle').textContent=t[1]}window.scrollTo(0,0)}
document.querySelectorAll('.side nav button').forEach(b=>b.onclick=()=>nav(b.dataset.p));
$('quick').onclick=()=>{const p=document.querySelector('main>section:not(.hidden)')?.id||'dashboard';if(p==='dashboard')nav('sales');else if(p==='investments')togglePanel('investmentForm');else if(p==='inventory')togglePanel('productForm');else if(p==='expenses')togglePanel('expenseForm');else nav('dashboard')};
$('if').onsubmit=e=>{e.preventDefault();const c=$('icur').value;db.investments.push({id:uid(),name:$('iname').value.trim(),date:$('idate').value||today(),cur:c,merch:+$('imerch').value,ship:+$('iship').value||0,total:+$('imerch').value+(+$('iship').value||0),alloc:$('ialloc').value,rateSnapshot:rate(c)});e.target.reset();$('idate').value=today();save()};
$('pf').onsubmit=e=>{e.preventDefault();const q=+$('pqty').value;db.products.push({id:uid(),name:$('pname').value.trim(),invId:$('pinv').value,style:($('pstyle').value||'').trim(),sku:($('psku').value||'').trim(),qty:q,stock:q,cost:+$('pcost').value,price:+$('pprice').value,cur:$('pcur').value,barcode:($('pbar').value||'').trim()});e.target.reset();save()};
function fillSale(){const p=prod($('sprod').value);if(p){$('sprice').value=p.price;$('scur').value=p.cur;preview()}}
$('sprod').onchange=fillSale;
$('sq').oninput=preview;$('sprice').oninput=preview;$('scur').onchange=preview;
$('sbar').oninput=function(){const q=this.value.trim().toLowerCase();if(!q)return;const p=db.products.find(x=>[x.barcode,x.sku,x.style,x.name].some(v=>String(v||'').toLowerCase()===q));if(p){$('sprod').value=p.id;fillSale()}else{$('preview').textContent='No hay ningún producto registrado con ese identificador.';$('salePreviewSide').textContent='Identificador no registrado.'}};
function preview(){const p=prod($('sprod').value);if(!p)return;const q=Math.max(1,+$('sq').value||1),revenue=cup((+$('sprice').value||0)*q,$('scur').value),cost=landed(p)*q,profit=revenue-cost;$('preview').textContent=`Stock disponible: ${p.stock} · Costo puesto: ${money(cost)} · Ganancia estimada: ${money(profit)}`;$('salePreviewSide').innerHTML=`<div><b>${p.name}</b><p>Stock: ${p.stock}</p><p>Costo puesto: ${money(landed(p))}</p><p>Venta: ${fmt(+$('sprice').value||0,$('scur').value)}</p><strong>${money(profit)} de ganancia estimada</strong></div>`}
$('sf').onsubmit=e=>{e.preventDefault();const p=prod($('sprod').value),q=+$('sq').value;if(!p||q<1||q>p.stock)return alert('Revisa el producto y la cantidad disponible.');const c=$('scur').value;db.sales.push({id:uid(),date:$('sdate').value||today(),prodId:p.id,qty:q,price:+$('sprice').value,cur:c,pay:$('spay').value,rateSnapshot:rate(c)});p.stock-=q;e.target.reset();$('sdate').value=today();save()};
$('ef').onsubmit=e=>{e.preventDefault();const c=$('ecur').value;db.expenses.push({id:uid(),date:$('edate').value||today(),desc:$('edesc').value.trim(),amt:+$('eamt').value,cur:c,rateSnapshot:rate(c)});e.target.reset();$('edate').value=today();save()};
$('rf').onsubmit=e=>{e.preventDefault();db.rates.USD=+$('rusd').value||db.rates.USD;db.rates.EUR=+$('reur').value||db.rates.EUR;save();alert('Tasas actualizadas')};
function table(x){return`<div class="table"><table>${x}</table></div>`}
function render(){const m=metrics();$('balance').textContent=money(Math.max(0,m.sales-m.expenses));$('recovered').textContent=money(Math.min(m.invested,m.cost));$('invested').textContent=money(m.invested);$('salesKpi').textContent=money(m.sales);$('gross').textContent=money(m.gross);$('net').textContent=money(m.net);$('rusd').value=db.rates.USD;$('reur').value=db.rates.EUR;
$('pinv').innerHTML=db.investments.map(i=>`<option value="${i.id}">${i.name}</option>`).join('')||'<option value="">Crea una inversión primero</option>';
$('sprod').innerHTML=db.products.map(p=>`<option value="${p.id}">${p.name} — stock ${p.stock}</option>`).join('')||'<option value="">Sin productos</option>';if(db.products.length)fillSale();
$('it').innerHTML=db.investments.length?table('<tr><th>Referencia</th><th>Total</th><th>Recuperación</th><th>Estado</th></tr>'+db.investments.map(i=>{const r=recovery(i);return`<tr><td><b>${i.name}</b><br><small>${i.date} · ${i.cur}</small></td><td>${fmt(i.total,i.cur)}</td><td>${r.pct.toFixed(1)}%<div class="progress"><i style="width:${r.pct}%"></i></div></td><td>${r.date?'Recuperada '+r.date:'En recuperación'}</td></tr>`}).join('')):'<p class="hint">No hay inversiones registradas.</p>';
renderProducts();$('st').innerHTML=db.sales.length?table('<tr><th>Fecha</th><th>Producto</th><th>Cant.</th><th>Venta</th><th>Costo</th><th>Ganancia</th><th>Cobro</th></tr>'+db.sales.slice().reverse().map(s=>{const p=prod(s.prodId),rev=cup(s.price*s.qty,s.cur,s.rateSnapshot),co=p?landed(p)*s.qty:0;return`<tr><td>${s.date}</td><td>${p?.name||'—'}</td><td>${s.qty}</td><td>${fmt(s.price*s.qty,s.cur)}</td><td>${money(co)}</td><td>${money(rev-co)}</td><td>${s.pay||'—'}</td></tr>`}).join('')):'<p class="hint">No hay ventas registradas.</p>';
$('et').innerHTML=db.expenses.length?table('<tr><th>Fecha</th><th>Concepto</th><th>Importe</th><th>En CUP</th></tr>'+db.expenses.slice().reverse().map(e=>`<tr><td>${e.date}</td><td>${e.desc}</td><td>${fmt(e.amt,e.cur)}</td><td>${money(cup(e.amt,e.cur,e.rateSnapshot))}</td></tr>`).join('')):'<p class="hint">No hay gastos registrados.</p>';
$('recovery').innerHTML=db.investments.map(i=>{const r=recovery(i);return`<div style="padding:9px 0"><div style="display:flex;justify-content:space-between"><b>${i.name}</b><span>${r.pct.toFixed(1)}%</span></div><div class="progress"><i style="width:${r.pct}%"></i></div><small style="color:var(--muted)">${r.date?'Recuperada '+r.date:'Aún en recuperación'}</small></div>`}).join('')||'<p style="color:var(--muted)">Agrega una inversión para comenzar.</p>';
$('recent').innerHTML=db.sales.slice().reverse().slice(0,5).map(s=>`<div class="recent"><span>${prod(s.prodId)?.name||'—'}<small>${s.date}</small></span><b>${money(cup(s.price*s.qty,s.cur,s.rateSnapshot))}</b></div>`).join('')||'<p style="color:var(--muted)">Aún no hay ventas.</p>';
const days=[];for(let n=13;n>=0;n--){const d=new Date();d.setDate(d.getDate()-n);days.push(d.toISOString().slice(0,10))}const vals=days.map(d=>db.sales.filter(s=>s.date===d).reduce((a,s)=>a+cup(s.price*s.qty,s.cur,s.rateSnapshot),0)),mx=Math.max(...vals,1);$('chart').innerHTML=vals.map(v=>`<div class="bar" style="height:${Math.max(3,v/mx*90)}%" title="${money(v)}"></div>`).join('');
const low=db.products.filter(p=>p.stock<=2).length;const pending=Math.max(0,m.invested-m.cost);$('invTotalStat').textContent=money(m.invested);$('invCountStat').textContent=db.investments.length;$('invPendingStat').textContent=money(pending);$('prodCountStat').textContent=db.products.length;$('stockCountStat').textContent=db.products.reduce((a,p)=>a+(+p.stock||0),0);$('lowStockStat').textContent=low;$('expenseTotalStat').textContent=money(m.expenses);$('expenseCountStat').textContent=db.expenses.length;$('netStat').textContent=money(m.net);
$('reportsBox').innerHTML=`<div class="report-grid"><div class="report-card"><small>Margen bruto</small><b>${m.sales?(m.gross/m.sales*100).toFixed(1):0}%</b></div><div class="report-card"><small>Capital pendiente</small><b>${money(pending)}</b></div><div class="report-card"><small>Ganancia neta</small><b>${money(m.net)}</b></div></div><div class="card"><h3>Lectura rápida</h3><p>Ventas registradas: <b>${db.sales.length}</b>. Productos en inventario: <b>${db.products.length}</b>. Gastos: <b>${db.expenses.length}</b>.</p></div>`}
function renderProducts(){const q=($('inventorySearch')?.value||'').trim().toLowerCase(),low=$('stockFilter')?.classList.contains('active');let ps=db.products.filter(p=>{const match=!q||[p.name,p.sku,p.style,p.barcode].some(v=>String(v||'').toLowerCase().includes(q));return match&&(!low||p.stock<=2)});$('pt').innerHTML=ps.length?table('<tr><th>Producto</th><th>Stock</th><th>Costo puesto</th><th>Precio</th><th>Identificadores</th></tr>'+ps.map(p=>`<tr><td><b>${p.name}</b><br><small>${inv(p.invId)?.name||'Sin inversión'}</small></td><td><b>${p.stock}</b>/${p.qty}</td><td>${money(landed(p))}</td><td>${fmt(p.price,p.cur)}</td><td><small>Estilo: ${p.style||'—'} · SKU: ${p.sku||'—'} · Código: ${p.barcode||'—'}</small></td></tr>`).join('')):'<p class="hint">No hay productos que coincidan.</p>'}
$('inventorySearch').oninput=renderProducts;$('stockFilter').onclick=function(){this.classList.toggle('active');renderProducts()};
$('export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='control_empresarial_respaldo.json';a.click()};
$('import').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{db=Object.assign({investments:[],products:[],sales:[],expenses:[],rates:{USD:360,EUR:390}},JSON.parse(r.result));save();alert('Importación completada')}catch(_){alert('JSON inválido')}};r.readAsText(f)};
$('clear').onclick=()=>{if(confirm('¿Borrar todos los datos guardados en este dispositivo?')){localStorage.removeItem(KEY);location.reload()}};
['idate','sdate','edate'].forEach(x=>$(x).value=today());render();nav('dashboard');
